"""
DAV1D Extended Emoji Dictionary - Part 2: Objects, Symbols & Flags
Continuation of the comprehensive Unicode 17.0 emoji vocabulary
"""

# ══════════════════════════════════════════════════════════════════════════════
# 🎮 GAMES & SPORTS EQUIPMENT
# ══════════════════════════════════════════════════════════════════════════════

SPORT_EQUIPMENT = {
    'ice_skate': '⛸',
    'fishing': '🎣',
    'diving_mask': '🤿',
    'running_shirt': '🎽',
    'skis': '🎿',
    'sled': '🛷',
    'curling': '🥌',
}

GAME = {
    'bullseye': '🎯',
    'dart': '🎯',
    'yoyo': '🪀',
    'kite': '🪁',
    'water_pistol': '🔫',
    'gun': '🔫',
    '8ball': '🎱',
    'pool': '🎱',
    'crystal_ball': '🔮',
    'fortune': '🔮',
    'magic_wand': '🪄',
    'wand': '🪄',
    'video_game': '🎮',
    'gaming': '🎮',
    'joystick': '🕹',
    'slot_machine': '🎰',
    'slots': '🎰',
    'dice': '🎲',
    'die': '🎲',
    'puzzle': '🧩',
    'teddy_bear': '🧸',
    'bear_toy': '🧸',
    'pinata': '🪅',
    'mirror_ball': '🪩',
    'disco': '🪩',
    'nesting_dolls': '🪆',
    'spade': '♠',
    'heart_suit': '♥',
    'diamond_suit': '♦',
    'club': '♣',
    'chess': '♟',
    'joker': '🃏',
    'mahjong': '🀄',
    'flower_cards': '🎴',
}

ARTS_CRAFTS = {
    'performing_arts': '🎭',
    'theater': '🎭',
    'drama': '🎭',
    'framed_picture': '🖼',
    'picture': '🖼',
    'palette': '🎨',
    'paint': '🎨',
    'thread': '🧵',
    'sewing_needle': '🪡',
    'needle': '🪡',
    'yarn': '🧶',
    'knot': '🪢',
}

# ══════════════════════════════════════════════════════════════════════════════
# 👕 CLOTHING & ACCESSORIES
# ══════════════════════════════════════════════════════════════════════════════

CLOTHING = {
    'glasses': '👓',
    'sunglasses': '🕶',
    'shades': '🕶',
    'goggles': '🥽',
    'lab_coat': '🥼',
    'safety_vest': '🦺',
    'necktie': '👔',
    'tie': '👔',
    'tshirt': '👕',
    'shirt': '👕',
    'jeans': '👖',
    'pants': '👖',
    'scarf': '🧣',
    'gloves': '🧤',
    'coat': '🧥',
    'jacket': '🧥',
    'socks': '🧦',
    'dress': '👗',
    'kimono': '👘',
    'sari': '🥻',
    'swimsuit': '🩱',
    'briefs': '🩲',
    'shorts': '🩳',
    'bikini': '👙',
    'womans_clothes': '👚',
    'fan': '🪭',
    'purse': '👛',
    'handbag': '👜',
    'bag': '👜',
    'clutch': '👝',
    'shopping_bags': '🛍',
    'shopping': '🛍',
    'backpack': '🎒',
    'sandal': '🩴',
    'shoe': '👞',
    'sneaker': '👟',
    'running_shoe': '👟',
    'boot': '🥾',
    'hiking_boot': '🥾',
    'flat_shoe': '🥿',
    'high_heel': '👠',
    'heel': '👠',
    'womans_sandal': '👡',
    'ballet_shoes': '🩰',
    'womans_boot': '👢',
    'hair_pick': '🪮',
    'crown': '👑',
    'womans_hat': '👒',
    'top_hat': '🎩',
    'graduation_cap': '🎓',
    'grad_cap': '🎓',
    'cap': '🧢',
    'baseball_cap': '🧢',
    'helmet': '🪖',
    'military_helmet': '🪖',
    'rescue_helmet': '⛑',
    'prayer_beads': '📿',
    'lipstick': '💄',
    'ring': '💍',
    'gem': '💎',
    'diamond': '💎',
}

# ══════════════════════════════════════════════════════════════════════════════
# 🔊 SOUND & MUSIC
# ══════════════════════════════════════════════════════════════════════════════

SOUND = {
    'muted': '🔇',
    'mute': '🔇',
    'speaker_low': '🔈',
    'speaker_medium': '🔉',
    'speaker_high': '🔊',
    'loud': '🔊',
    'loudspeaker': '📢',
    'megaphone': '📣',
    'horn': '📯',
    'bell': '🔔',
    'no_bell': '🔕',
}

MUSIC = {
    'musical_score': '🎼',
    'sheet_music': '🎼',
    'note': '🎵',
    'notes': '🎶',
    'music': '🎶',
    'studio_mic': '🎙',
    'level_slider': '🎚',
    'slider': '🎚',
    'control_knobs': '🎛',
    'knobs': '🎛',
    'microphone': '🎤',
    'mic': '🎤',
    'headphone': '🎧',
    'headphones': '🎧',
    'radio': '📻',
}

MUSICAL_INSTRUMENT = {
    'saxophone': '🎷',
    'sax': '🎷',
    'trumpet': '🎺',
    'trombone': '🪊',
    'accordion': '🪗',
    'guitar': '🎸',
    'keyboard': '🎹',
    'piano': '🎹',
    'violin': '🎻',
    'banjo': '🪕',
    'drum': '🥁',
    'drums': '🥁',
    'long_drum': '🪘',
    'maracas': '🪇',
    'flute': '🪈',
    'harp': '🪉',
}

# ══════════════════════════════════════════════════════════════════════════════
# 📱 ELECTRONICS & TECHNOLOGY
# ══════════════════════════════════════════════════════════════════════════════

PHONE = {
    'mobile': '📱',
    'phone': '📱',
    'cell': '📱',
    'calling': '📲',
    'telephone': '☎',
    'receiver': '📞',
    'pager': '📟',
    'fax': '📠',
}

COMPUTER = {
    'battery': '🔋',
    'low_battery': '🪫',
    'plug': '🔌',
    'laptop': '💻',
    'computer': '💻',
    'desktop': '🖥',
    'printer': '🖨',
    'print': '🖨',
    'keyboard': '⌨',
    'mouse': '🖱',
    'trackball': '🖲',
    'disk': '💽',
    'floppy': '💾',
    'cd': '💿',
    'dvd': '📀',
    'abacus': '🧮',
}

LIGHT_VIDEO = {
    'movie_camera': '🎥',
    'camera': '🎥',
    'film_frames': '🎞',
    'projector': '📽',
    'clapper': '🎬',
    'clapperboard': '🎬',
    'tv': '📺',
    'television': '📺',
    'camera_photo': '📷',
    'camera_flash': '📸',
    'photo': '📸',
    'video_camera': '📹',
    'videocassette': '📼',
    'vhs': '📼',
    'mag_left': '🔍',
    'search_left': '🔍',
    'mag_right': '🔎',
    'search_right': '🔎',
    'candle': '🕯',
    'bulb': '💡',
    'idea': '💡',
    'flashlight': '🔦',
    'torch': '🔦',
    'lantern': '🏮',
    'diya_lamp': '🪔',
}

# ══════════════════════════════════════════════════════════════════════════════
# 📚 BOOKS, PAPER & OFFICE
# ══════════════════════════════════════════════════════════════════════════════

BOOK_PAPER = {
    'notebook_cover': '📔',
    'closed_book': '📕',
    'open_book': '📖',
    'book': '📖',
    'green_book': '📗',
    'blue_book': '📘',
    'orange_book': '📙',
    'books': '📚',
    'notebook': '📓',
    'ledger': '📒',
    'page_curl': '📃',
    'scroll': '📜',
    'page': '📄',
    'newspaper': '📰',
    'news': '📰',
    'rolled_newspaper': '🗞',
    'bookmark_tabs': '📑',
    'tabs': '📑',
    'bookmark': '🔖',
    'label': '🏷',
    'tag': '🏷',
}

MONEY = {
    'coin': '🪙',
    'money_bag': '💰',
    'treasure': '🪎',
    'yen': '💴',
    'dollar': '💵',
    'euro': '💶',
    'pound': '💷',
    'money_wings': '💸',
    'flying_money': '💸',
    'credit_card': '💳',
    'card': '💳',
    'receipt': '🧾',
    'chart_yen': '💹',
}

MAIL = {
    'envelope': '✉',
    'email': '📧',
    'incoming': '📨',
    'outgoing': '📩',
    'outbox': '📤',
    'inbox': '📥',
    'package': '📦',
    'box': '📦',
    'mailbox_closed': '📫',
    'mailbox': '📫',
    'mailbox_no_mail': '📪',
    'mailbox_mail': '📬',
    'mailbox_no_flag': '📭',
    'postbox': '📮',
    'ballot_box': '🗳',
    'ballot': '🗳',
}

WRITING = {
    'pencil': '✏',
    'black_nib': '✒',
    'nib': '✒',
    'fountain_pen': '🖋',
    'pen': '🖊',
    'paintbrush': '🖌',
    'brush': '🖌',
    'crayon': '🖍',
    'memo': '📝',
    'note': '📝',
}

OFFICE = {
    'briefcase': '💼',
    'business': '💼',
    'folder': '📁',
    'open_folder': '📂',
    'dividers': '🗂',
    'calendar': '📅',
    'tear_off_calendar': '📆',
    'notepad': '🗒',
    'spiral_calendar': '🗓',
    'card_index': '📇',
    'increasing': '📈',
    'up_chart': '📈',
    'decreasing': '📉',
    'down_chart': '📉',
    'bar_chart': '📊',
    'stats': '📊',
    'clipboard': '📋',
    'pushpin': '📌',
    'pin': '📌',
    'round_pushpin': '📍',
    'location': '📍',
    'paperclip': '📎',
    'clip': '📎',
    'linked_paperclips': '🖇',
    'straight_ruler': '📏',
    'ruler': '📏',
    'triangular_ruler': '📐',
    'triangle_ruler': '📐',
    'scissors': '✂',
    'cut': '✂',
    'card_file_box': '🗃',
    'file_cabinet': '🗄',
    'cabinet': '🗄',
    'wastebasket': '🗑',
    'trash': '🗑',
}

# ══════════════════════════════════════════════════════════════════════════════
# 🔧 TOOLS & EQUIPMENT
# ══════════════════════════════════════════════════════════════════════════════

LOCK = {
    'locked': '🔒',
    'lock': '🔒',
    'unlocked': '🔓',
    'unlock': '🔓',
    'locked_pen': '🔏',
    'locked_key': '🔐',
    'key': '🔑',
    'old_key': '🗝',
}

TOOL = {
    'hammer': '🔨',
    'axe': '🪓',
    'pick': '⛏',
    'pickaxe': '⛏',
    'hammer_pick': '⚒',
    'hammer_wrench': '🛠',
    'tools': '🛠',
    'dagger': '🗡',
    'knife_weapon': '🗡',
    'crossed_swords': '⚔',
    'swords': '⚔',
    'bomb': '💣',
    'boomerang': '🪃',
    'bow_arrow': '🏹',
    'archery': '🏹',
    'shield': '🛡',
    'saw': '🪚',
    'carpentry_saw': '🪚',
    'wrench': '🔧',
    'screwdriver': '🪛',
    'nut_bolt': '🔩',
    'bolt': '🔩',
    'gear': '⚙',
    'cog': '⚙',
    'clamp': '🗜',
    'scale': '⚖',
    'balance': '⚖',
    'cane': '🦯',
    'white_cane': '🦯',
    'link': '🔗',
    'broken_chain': '⛓️‍💥',
    'chains': '⛓',
    'hook': '🪝',
    'toolbox': '🧰',
    'magnet': '🧲',
    'ladder': '🪜',
    'shovel': '🪏',
}

SCIENCE = {
    'alembic': '⚗',
    'test_tube': '🧪',
    'petri_dish': '🧫',
    'dna': '🧬',
    'microscope': '🔬',
    'telescope': '🔭',
    'satellite_antenna': '📡',
    'antenna': '📡',
}

MEDICAL = {
    'syringe': '💉',
    'blood': '🩸',
    'pill': '💊',
    'medicine': '💊',
    'bandage': '🩹',
    'crutch': '🩼',
    'stethoscope': '🩺',
    'xray': '🩻',
}

# ══════════════════════════════════════════════════════════════════════════════
# 🏠 HOUSEHOLD ITEMS
# ══════════════════════════════════════════════════════════════════════════════

HOUSEHOLD = {
    'door': '🚪',
    'elevator': '🛗',
    'lift': '🛗',
    'mirror': '🪞',
    'window': '🪟',
    'bed': '🛏',
    'couch': '🛋',
    'sofa': '🛋',
    'chair': '🪑',
    'toilet': '🚽',
    'plunger': '🪠',
    'shower': '🚿',
    'bathtub': '🛁',
    'tub': '🛁',
    'mouse_trap': '🪤',
    'trap': '🪤',
    'razor': '🪒',
    'lotion': '🧴',
    'safety_pin': '🧷',
    'broom': '🧹',
    'basket': '🧺',
    'toilet_paper': '🧻',
    'bucket': '🪣',
    'soap': '🧼',
    'bubbles': '🫧',
    'toothbrush': '🪥',
    'sponge': '🧽',
    'fire_extinguisher': '🧯',
    'extinguisher': '🧯',
    'cart': '🛒',
    'shopping_cart': '🛒',
}

OTHER_OBJECT = {
    'cigarette': '🚬',
    'smoking': '🚬',
    'coffin': '⚰',
    'headstone': '🪦',
    'grave': '🪦',
    'urn': '⚱',
    'nazar': '🧿',
    'evil_eye': '🧿',
    'hamsa': '🪬',
    'moai': '🗿',
    'statue': '🗿',
    'placard': '🪧',
    'sign': '🪧',
    'id_card': '🪪',
    'id': '🪪',
}

# ══════════════════════════════════════════════════════════════════════════════
# ⚠️ SYMBOLS & SIGNS
# ══════════════════════════════════════════════════════════════════════════════

TRANSPORT_SIGN = {
    'atm': '🏧',
    'litter_bin': '🚮',
    'potable_water': '🚰',
    'drinking_water': '🚰',
    'wheelchair': '♿',
    'mens_room': '🚹',
    'mens': '🚹',
    'womens_room': '🚺',
    'womens': '🚺',
    'restroom': '🚻',
    'bathroom': '🚻',
    'baby_symbol': '🚼',
    'baby_sign': '🚼',
    'wc': '🚾',
    'water_closet': '🚾',
    'passport_control': '🛂',
    'passport': '🛂',
    'customs': '🛃',
    'baggage_claim': '🛄',
    'luggage_claim': '🛄',
    'left_luggage': '🛅',
}

WARNING = {
    'warning': '⚠',
    'caution': '⚠',
    'children_crossing': '🚸',
    'no_entry': '⛔',
    'prohibited': '🚫',
    'no_bikes': '🚳',
    'no_smoking': '🚭',
    'no_littering': '🚯',
    'non_potable': '🚱',
    'no_pedestrians': '🚷',
    'no_phones': '📵',
    'no_under_18': '🔞',
    'adults_only': '🔞',
    'radioactive': '☢',
    'biohazard': '☣',
}

ARROW = {
    'up_arrow': '⬆',
    'up_right': '↗',
    'right_arrow': '➡',
    'down_right': '↘',
    'down_arrow': '⬇',
    'down_left': '↙',
    'left_arrow': '⬅',
    'up_left': '↖',
    'up_down': '↕',
    'left_right': '↔',
    'right_curve_left': '↩',
    'left_curve_right': '↪',
    'curve_up': '⤴',
    'curve_down': '⤵',
    'clockwise': '🔃',
    'counterclockwise': '🔄',
    'back': '🔙',
    'end': '🔚',
    'on': '🔛',
    'soon': '🔜',
    'top': '🔝',
}

RELIGION = {
    'worship': '🛐',
    'atom': '⚛',
    'om': '🕉',
    'star_of_david': '✡',
    'wheel_dharma': '☸',
    'yin_yang': '☯',
    'latin_cross': '✝',
    'orthodox_cross': '☦',
    'star_crescent': '☪',
    'peace': '☮',
    'peace_symbol': '☮',
    'menorah': '🕎',
    'dotted_star': '🔯',
    'khanda': '🪯',
}

ZODIAC = {
    'aries': '♈',
    'taurus': '♉',
    'gemini': '♊',
    'cancer': '♋',
    'leo': '♌',
    'virgo': '♍',
    'libra': '♎',
    'scorpio': '♏',
    'sagittarius': '♐',
    'capricorn': '♑',
    'aquarius': '♒',
    'pisces': '♓',
    'ophiuchus': '⛎',
}

AV_SYMBOL = {
    'shuffle': '🔀',
    'repeat': '🔁',
    'repeat_one': '🔂',
    'play': '▶',
    'fast_forward': '⏩',
    'ff': '⏩',
    'next': '⏭',
    'play_pause': '⏯',
    'reverse': '◀',
    'rewind': '⏪',
    'previous': '⏮',
    'prev': '⏮',
    'up_button': '🔼',
    'fast_up': '⏫',
    'down_button': '🔽',
    'fast_down': '⏬',
    'pause': '⏸',
    'stop': '⏹',
    'record': '⏺',
    'eject': '⏏',
    'cinema': '🎦',
    'movies': '🎦',
    'dim': '🔅',
    'bright': '🔆',
    'signal': '📶',
    'wifi': '🛜',
    'wireless': '🛜',
    'vibration': '📳',
    'phone_off': '📴',
}

GENDER = {
    'female': '♀',
    'male': '♂',
    'transgender': '⚧',
}

MATH = {
    'multiply': '✖',
    'times': '✖',
    'plus': '➕',
    'add': '➕',
    'minus': '➖',
    'subtract': '➖',
    'divide': '➗',
    'equals': '🟰',
    'infinity': '♾',
}

OTHER_SYMBOL = {
    'medical': '⚕',
    'recycle': '♻',
    'recycling': '♻',
    'fleur_de_lis': '⚜',
    'trident': '🔱',
    'name_badge': '📛',
    'badge': '📛',
    'beginner': '🔰',
    'hollow_circle': '⭕',
    'o': '⭕',
    'check_button': '✅',
    'checkbox': '☑',
    'checkmark': '✔',
    'x': '❌',
    'cross_button': '❎',
    'curly_loop': '➰',
    'double_loop': '➿',
    'asterisk': '✳',
    'star_8': '✴',
    'sparkle': '❇',
    'copyright': '©',
    'registered': '®',

OTHER_OBJECT = {
    'cigarette': '🚬',
    'smoking': '🚬',
    'coffin': '⚰',
    'headstone': '🪦',
    'grave': '🪦',
    'urn': '⚱',
    'nazar': '🧿',
    'evil_eye': '🧿',
    'hamsa': '🪬',
    'moai': '🗿',
    'statue': '🗿',
    'placard': '🪧',
    'sign': '🪧',
    'id_card': '🪪',
    'id': '🪪',
}

# ══════════════════════════════════════════════════════════════════════════════
# ⚠️ SYMBOLS & SIGNS
# ══════════════════════════════════════════════════════════════════════════════

TRANSPORT_SIGN = {
    'atm': '🏧',
    'litter_bin': '🚮',
    'potable_water': '🚰',
    'drinking_water': '🚰',
    'wheelchair': '♿',
    'mens_room': '🚹',
    'mens': '🚹',
    'womens_room': '🚺',
    'womens': '🚺',
    'restroom': '🚻',
    'bathroom': '🚻',
    'baby_symbol': '🚼',
    'baby_sign': '🚼',
    'wc': '🚾',
    'water_closet': '🚾',
    'passport_control': '🛂',
    'passport': '🛂',
    'customs': '🛃',
    'baggage_claim': '🛄',
    'luggage_claim': '🛄',
    'left_luggage': '🛅',
}

WARNING = {
    'warning': '⚠',
    'caution': '⚠',
    'children_crossing': '🚸',
    'no_entry': '⛔',
    'prohibited': '🚫',
    'no_bikes': '🚳',
    'no_smoking': '🚭',
    'no_littering': '🚯',
    'non_potable': '🚱',
    'no_pedestrians': '🚷',
    'no_phones': '📵',
    'no_under_18': '🔞',
    'adults_only': '🔞',
    'radioactive': '☢',
    'biohazard': '☣',
}

ARROW = {
    'up_arrow': '⬆',
    'up_right': '↗',
    'right_arrow': '➡',
    'down_right': '↘',
    'down_arrow': '⬇',
    'down_left': '↙',
    'left_arrow': '⬅',
    'up_left': '↖',
    'up_down': '↕',
    'left_right': '↔',
    'right_curve_left': '↩',
    'left_curve_right': '↪',
    'curve_up': '⤴',
    'curve_down': '⤵',
    'clockwise': '🔃',
    'counterclockwise': '🔄',
    'back': '🔙',
    'end': '🔚',
    'on': '🔛',
    'soon': '🔜',
    'top': '🔝',
}

RELIGION = {
    'worship': '🛐',
    'atom': '⚛',
    'om': '🕉',
    'star_of_david': '✡',
    'wheel_dharma': '☸',
    'yin_yang': '☯',
    'latin_cross': '✝',
    'orthodox_cross': '☦',
    'star_crescent': '☪',
    'peace': '☮',
    'peace_symbol': '☮',
    'menorah': '🕎',
    'dotted_star': '🔯',
    'khanda': '🪯',
}

ZODIAC = {
    'aries': '♈',
    'taurus': '♉',
    'gemini': '♊',
    'cancer': '♋',
    'leo': '♌',
    'virgo': '♍',
    'libra': '♎',
    'scorpio': '♏',
    'sagittarius': '♐',
    'capricorn': '♑',
    'aquarius': '♒',
    'pisces': '♓',
    'ophiuchus': '⛎',
}

AV_SYMBOL = {
    'shuffle': '🔀',
    'repeat': '🔁',
    'repeat_one': '🔂',
    'play': '▶',
    'fast_forward': '⏩',
    'ff': '⏩',
    'next': '⏭',
    'play_pause': '⏯',
    'reverse': '◀',
    'rewind': '⏪',
    'previous': '⏮',
    'prev': '⏮',
    'up_button': '🔼',
    'fast_up': '⏫',
    'down_button': '🔽',
    'fast_down': '⏬',
    'pause': '⏸',
    'stop': '⏹',
    'record': '⏺',
    'eject': '⏏',
    'cinema': '🎦',
    'movies': '🎦',
    'dim': '🔅',
    'bright': '🔆',
    'signal': '📶',
    'wifi': '🛜',
    'wireless': '🛜',
    'vibration': '📳',
    'phone_off': '📴',
}

GENDER = {
    'female': '♀',
    'male': '♂',
    'transgender': '⚧',
}

MATH = {
    'multiply': '✖',
    'times': '✖',
    'plus': '➕',
    'add': '➕',
    'minus': '➖',
    'subtract': '➖',
    'divide': '➗',
    'equals': '🟰',
    'infinity': '♾',
}

OTHER_SYMBOL = {
    'medical': '⚕',
    'recycle': '♻',
    'recycling': '♻',
    'fleur_de_lis': '⚜',
    'trident': '🔱',
    'name_badge': '📛',
    'badge': '📛',
    'beginner': '🔰',
    'hollow_circle': '⭕',
    'o': '⭕',
    'check_button': '✅',
    'checkbox': '☑',
    'checkmark': '✔',
    'x': '❌',
    'cross_button': '❎',
    'curly_loop': '➰',
    'double_loop': '➿',
    'asterisk': '✳',
    'star_8': '✴',
    'sparkle': '❇',
    'copyright': '©',
    'registered': '®',
    'trademark': '™',
    'tm': '™',
    'splatter': '🫟',
}

# ══════════════════════════════════════════════════════════════════════════════
# 🏁 FLAGS
# ══════════════════════════════════════════════════════════════════════════════

FLAG = {
    'checkered': '🏁',
    'racing': '🏁',
    'triangular': '🚩',
    'red_flag': '🚩',
    'crossed': '🎌',
    'black_flag': '🏴',
    'white_flag': '🏳',
    'rainbow': '🏳️‍🌈',
    'pride': '🏳️‍🌈',
    'transgender_flag': '🏳️‍⚧️',
    'trans_flag': '🏳️‍⚧️',
    'pirate': '🏴‍☠️',
    'jolly_roger': '🏴‍☠️',
}

# Country Flags (abbreviated selection - key countries)
COUNTRY_FLAG = {
    # Popular/Major countries
    'usa': '🇺🇸',
    'us': '🇺🇸',
    'america': '🇺🇸',
    'uk': '🇬🇧',
    'england': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'canada': '🇨🇦',
    'mexico': '🇲🇽',
    'brazil': '🇧🇷',
    'argentina': '🇦🇷',
    'france': '🇫🇷',
    'germany': '🇩🇪',
    'italy': '🇮🇹',
    'spain': '🇪🇸',
    'portugal': '🇵🇹',
    'russia': '🇷🇺',
    'china': '🇨🇳',
    'japan': '🇯🇵',
    'korea': '🇰🇷',
    'south_korea': '🇰🇷',
    'india': '🇮🇳',
    'australia': '🇦🇺',
    'new_zealand': '🇳🇿',
    'south_africa': '🇿🇦',
    'egypt': '🇪🇬',
    'nigeria': '🇳🇬',
    'israel': '🇮🇱',
    'saudi_arabia': '🇸🇦',
    'uae': '🇦🇪',
    'turkey': '🇹🇷',
    'sweden': '🇸🇪',
    'norway': '🇳🇴',
    'denmark': '🇩🇰',
    'finland': '🇫🇮',
    'netherlands': '🇳🇱',
    'belgium': '🇧🇪',
    'switzerland': '🇨🇭',
    'austria': '🇦🇹',
    'poland': '🇵🇱',
    'greece': '🇬🇷',
    'ireland': '🇮🇪',
    'ukraine': '🇺🇦',
    'thailand': '🇹🇭',
    'vietnam': '🇻🇳',
    'singapore': '🇸🇬',
    'hong_kong': '🇭🇰',
    'indonesia': '🇮🇩',
    'philippines': '🇵🇭',
    'malaysia': '🇲🇾',
    'pakistan': '🇵🇰',
    'bangladesh': '🇧🇩',
    'chile': '🇨🇱',
    'colombia': '🇨🇴',
    'peru': '🇵🇪',
    'venezuela': '🇻🇪',
    'cuba': '🇨🇺',
    'jamaica': '🇯🇲',
    'kenya': '🇰🇪',
    'ethiopia': '🇪🇹',
    'ghana': '🇬🇭',
    'tanzania': '🇹🇿',
    'morocco': '🇲🇦',
    'algeria': '🇩🇿',
    'tunisia': '🇹🇳',
    'libya': '🇱🇾',
    'iraq': '🇮🇶',
    'iran': '🇮🇷',
    'afghanistan': '🇦🇫',
    'syria': '🇸🇾',
    'jordan': '🇯🇴',
    'lebanon': '🇱🇧',
    'yemen': '🇾🇪',
    'kuwait': '🇰🇼',
    'qatar': '🇶🇦',
    'bahrain': '🇧🇭',
    'oman': '🇴🇲',
    # Additional countries
    'albania': '🇦🇱',
    'andorra': '🇦🇩',
    'armenia': '🇦🇲',
    'azerbaijan': '🇦🇿',
    'belarus': '🇧🇾',
    'bosnia': '🇧🇦',
    'bulgaria': '🇧🇬',
    'croatia': '🇭🇷',
    'cyprus': '🇨🇾',
    'czechia': '🇨🇿',
    'estonia': '🇪🇪',
    'georgia': '🇬🇪',
    'hungary': '🇭🇺',
    'iceland': '🇮🇸',
    'kosovo': '🇽🇰',
    'latvia': '🇱🇻',
    'lithuania': '🇱🇹',
    'luxembourg': '🇱🇺',
    'malta': '🇲🇹',
    'moldova': '🇲🇩',
    'monaco': '🇲🇨',
    'montenegro': '🇲🇪',
    'north_macedonia': '🇲🇰',
    'romania': '🇷🇴',
    'san_marino': '🇸🇲',
    'serbia': '🇷🇸',
    'slovakia': '🇸🇰',
    'slovenia': '🇸🇮',
    'vatican': '🇻🇦',
    # Africa
    'angola': '🇦🇴',
    'benin': '🇧🇯',
    'botswana': '🇧🇼',
    'burkina_faso': '🇧🇫',
    'burundi': '🇧🇮',
    'cameroon': '🇨🇲',
    'cape_verde': '🇨🇻',
    'central_african_republic': '🇨🇫',
    'chad': '🇹🇩',
    'comoros': '🇰🇲',
    'congo': '🇨🇬',
    'djibouti': '🇩🇯',
    'equatorial_guinea': '🇬🇶',
    'eritrea': '🇪🇷',
    'eswatini': '🇸🇿',
    'gabon': '🇬🇦',
    'gambia': '🇬🇲',
    'guinea': '🇬🇳',
    'guinea_bissau': '🇬🇼',
    'ivory_coast': '🇨🇮',
    'lesotho': '🇱🇸',
    'liberia': '🇱🇷',
    'madagascar': '🇲🇬',
    'malawi': '🇲🇼',
    'mali': '🇲🇱',
    'mauritania': '🇲🇷',
    'mauritius': '🇲🇺',
    'mozambique': '🇲🇿',
    'namibia': '🇳🇦',
    'niger': '🇳🇪',
    'rwanda': '🇷🇼',
    'senegal': '🇸🇳',
    'seychelles': '🇸🇨',
    'sierra_leone': '🇸🇱',
    'somalia': '🇸🇴',
    'south_sudan': '🇸🇸',
    'sudan': '🇸🇩',
    'togo': '🇹🇬',
    'uganda': '🇺🇬',
    'zambia': '🇿🇲',
    'zimbabwe': '🇿🇼',
    # Asia & Pacific
    'brunei': '🇧🇳',
    'cambodia': '🇰🇭',
    'laos': '🇱🇦',
    'mongolia': '🇲🇳',
    'myanmar': '🇲🇲',
    'nepal': '🇳🇵',
    'bhutan': '🇧🇹',
    'sri_lanka': '🇱🇰',
    'maldives': '🇲🇻',
    'north_korea': '🇰🇵',
    'taiwan': '🇹🇼',
    'fiji': '🇫🇯',
    'papua_new_guinea': '🇵🇬',
    'samoa': '🇼🇸',
    'tonga': '🇹🇴',
    'vanuatu': '🇻🇺',
    # Americas
    'bahamas': '🇧🇸',
    'barbados': '🇧🇧',
    'belize': '🇧🇿',
    'bolivia': '🇧🇴',
    'costa_rica': '🇨🇷',
    'dominican_republic': '🇩🇴',
    'ecuador': '🇪🇨',
    'el_salvador': '🇸🇻',
    'guatemala': '🇬🇹',
    'haiti': '🇭🇹',
    'honduras': '🇭🇳',
    'nicaragua': '🇳🇮',
    'panama': '🇵🇦',
    'paraguay': '🇵🇾',
    'puerto_rico': '🇵🇷',
    'suriname': '🇸🇷',
    'trinidad': '🇹🇹',
    'uruguay': '🇺🇾',
    # Middle East & Central Asia
    'kazakhstan': '🇰🇿',
    'kyrgyzstan': '🇰🇬',
    'tajikistan': '🇹🇯',
    'turkmenistan': '🇹🇲',
    'uzbekistan': '🇺🇿',
    # Special
    'un': '🇺🇳',
    'united_nations': '🇺🇳',
    'eu': '🇪🇺',
    'european_union': '🇪🇺',
}

# Export all as one comprehensive dictionary
ALL_OBJECTS_SYMBOLS = {
    **SPORT_EQUIPMENT,
    **GAME,
    **ARTS_CRAFTS,
    **CLOTHING,
    **SOUND,
    **MUSIC,
    **MUSICAL_INSTRUMENT,
    **PHONE,
    **COMPUTER,
    **LIGHT_VIDEO,
    **BOOK_PAPER,
    **MONEY,
    **MAIL,
    **WRITING,
    **OFFICE,
    **LOCK,
    **TOOL,
    **SCIENCE,
    **MEDICAL,
    **HOUSEHOLD,
    **OTHER_OBJECT,
    **TRANSPORT_SIGN,
    **WARNING,
    **ARROW,
    **RELIGION,
    **ZODIAC,
    **AV_SYMBOL,
    **GENDER,
    **MATH,
    **OTHER_SYMBOL,
    **FLAG,
    **COUNTRY_FLAG,
}
